### ISSUE TITLE
Have some questions about using API ...

### ISSUE THREAD

**Issue by supernaughty** [gogs/docs-api#14]
Hello! i'm looking around community where i can ask a question, but i didn't find.. 
maybe this page is available to asking.. if I did a mistake, please forgive me.
and sorry for my bad english!! i will study english more..

by the way, I'm checking gogs for managing our projects!

We need to have access control function for each git repository, 
and we thought gogs is perfect answer.

for more efficiency, we are going to make automatic access control system for gogs, by using docs-api. I'm planning to make each repository will have read access team, read+wirte access team automatically.

this is my first time to using RESTful API, but some of api didn't working ..

by the CURL.EXE, i successfully used POST and GET method. for example, create a new repository, create a organization, team, list up all repositories, ... etc.

worked command::
curl -H "Content-Type: application/json" -H "Authorization: token 49289d2cbe69b8dcbc74cdbfa77a52c319ad31fe" -d "{""name"": ""newrepo"", ""private"": true}" -XPOST "http://localhost:3000/api/v1/admin/users/myeonghun.noh/repos"

but I failed for PUT method.. it didn't worked and I can't find its problem and knowing someone..

failed command::
curl -H "Content-Type: application/json" -H "Authorization: token 49289d2cbe69b8dcbc74cdbfa77a52c319ad31fe" -X PUT "http://localhost:3000/api/v1/admin/orgs/CDE-6666/teams/SW-1111-read/members/myeonghun.noh"

please help me.. T_T

**Comment by unknwon** [comment]
Hi,

First of all, it is not clear to me what is your expected input and output...

For example, the "worked command" has `"{""name"": ""newrepo"", ""private"": true}"`, and this is not even looking like a valid JSON to me, I suspect why it worked.

Please tell me:
1. What is the exact one goal you want to achieve and which API you used,
2. and what is expected result and what did you get instead.

Otherwise, I'm afraid I cannot be helpful at all. 

BTW, we have forum for asking questions: https://discuss.gogs.io/

**Comment by supernaughty** [comment]
thank you for your answer! I'm using CURL.EXE at window. i have to type " twice between { }
1. What is the exact one goal you want to achieve and which API you used,
     -> i'm going to use Add team membership api at https://github.com/gogs/docs-api/blob/master/Administration/Organizations.md
2. and what is expected result and what did you get instead.
     -> i thought  some json result message will returned, but no message has returned on my cmd.
          and gogs server log returned to me 404 not found..

**Comment by unknwon** [comment]
Which API exactly you're using?

**Comment by supernaughty** [comment]
I'm so sorry for my message looks not sure! It is because of my bad english skills..
I'm using RESTful API for gogs. I read from docs-api/Administration/Organizations.md 

**Add team membership**

>PUT /admin/teams/:teamid/members/:username

I thought there is no parameter in Add Team Membership, so I put like this

> curl -H "Content-Type: application/json" -H "Authorization: token 49289d2cbe69b8dcbc74cdbfa77a52c319ad31fe" -X PUT "http://localhost:3000/api/v1/admin/teams/SW-1111-read/members/myeonghun.noh"

And  command line returned nothing.. just blank! 
but gogs server (macaron) said it is 404!

**Comment by unknwon** [comment]
I think the problem is `:teamid`, it expects an integer (team's ID), not a string  (team's name).

**Comment by supernaughty** [comment]
Sorry for late! I checked this immediately after woke up! 
It was perfectly working! thank you so much!
