### ISSUE TITLE
API returns Unauthorized on some endpoints

### ISSUE THREAD

**Issue by nuddelaug** [gogs/docs-api#17]
when trying to retrieve a list of available repositories for the authenticated Users, the API returns 
(I've just removed the real address to avoid issues, but of course the host isn't localhost)

401: Unauthorized
r = requests.get('https://localhost/api/v1/repos/search?q=test&uid=1', auth=a, verify=False)
r
<Response [200]>
r.json()
{u'ok': True, u'data': [{u'website': u'', u'forks_count': 0, u'updated_at': u'2020-04-24T09:27:50Z', u'private': True, ...

r = requests.get('https://localhost/api/v1/user/repos', auth=a, verify=False)
r
<Response [401]>
r.reason
'Unauthorized'

I'm running _mixed_ User configurations with LDAP connected, might this be an issue ? (naa just tried it with a local created user as well ... fails)
Fetched the latest container today with following informations 

0.12.0+dev
Git-Version
2.24.1
Go-Version
go1.14.2
Build-Zeit
2020-04-21 10:12:22 UTC
Build-Commit
4e1f38ce28e87ece15a29c1f0fa2d7b5eeef79a6 

Image header
"Created": "2020-04-21T10:22:42.165889729Z",
"Id": "sha256:e69e22eb6cdaed593a443876d5ec766a885637d2678a24c93c833920b5eb80a3"

**Comment by unknwon** [comment]
Hi, that's because you need to authenticate your requests with access token: https://github.com/gogs/docs-api#access-token
