### ISSUE TITLE
about 403 question

### ISSUE THREAD

**Issue by Ivin-yang** [gogs/docs-api#19]
hi
url:http://192.168.60.175:3000/api/v1/admin/users/show/repos?token=b96ed14c42a1ed7f94c5d4e54d8e0ede0d7f9dad

response: 403Forbidden

I request that my local Gogs can add warehouses, but remote access to the server is not possible.

please tell me how can i solve this question.

thank you very much!

**Comment by Ivin-yang** [comment]
i think this is a cross-domain problem
i use postman  is ok 
but ajax is failure

**Comment by unknwon** [comment]
403 means the token you have provided does not have sufficient permissions to call this endpoint, you need to create a token from a site admin.
