### ISSUE TITLE
About basic authentication.

### ISSUE THREAD

**Issue by Ivin-yang** [gogs/docs-api#20]
hi
i wan to create a access key ,
but response is 401  mean not authority.
i know u have written notes 
Create a access token requires that you are authenticated via basic authentication.

how can i do it?
i use postman.

thank u very much!

**Comment by unknwon** [comment]
401 means you have not provided anything for basic authentication. Please attach screenshots of how you've used postman.

**Comment by Ivin-yang** [comment]
![微信截图_20200824085546](https://user-images.githubusercontent.com/60543550/90993596-15415d00-e5e8-11ea-891c-6917f5a2af58.png)
![微信截图_20200824085618](https://user-images.githubusercontent.com/60543550/90993602-18d4e400-e5e8-11ea-9bfa-52c22f6aafef.png)
there are my postman screenshot.

please tell me how can i add basic authentication?

Is there any information added to the request header?

thank u very much!

**Comment by unknwon** [comment]
https://community.postman.com/t/can-i-just-type-id-and-password-into-basic-auth-if-i-want-to-authenticate/6441

**Comment by Ivin-yang** [comment]
thank u very much!
i have solved my project!
but ,now , i have a new question.
see this picture!
![微信截图_20200825133618](https://user-images.githubusercontent.com/60543550/91127044-fde19d00-e6d7-11ea-9617-6dd02e7ae1a7.png)

![微信截图_20200825133426](https://user-images.githubusercontent.com/60543550/91126952-c1ae3c80-e6d7-11ea-96f7-4384d568a70d.png)

I want to get the data in the red box.
for example:
The historical data submitted by users .
The latest submission time and description of each document.

thank u !

**Comment by unknwon** [comment]
>The historical data submitted by users .
The latest submission time and description of each document.

Just click on gray labels on the SHA1 column.

**Comment by Ivin-yang** [comment]
i am sorry.
Maybe the question I asked, you did not understand.
i want to get these data by api.

The historical data submitted by users .
The latest submission time and description of each document.

**The page I made needs to display these data**

please tell me which api can get these data .

thank u !

**Comment by unknwon** [comment]
> i want to get these data by api.

Ah, OK.

Can you give examples for each these?
- The historical data submitted by users .
- The latest submission time and description of each document.

BTW, you could just read through this repository https://github.com/gogs/docs-api to find APIs :)

**Comment by t-walker-wei** [comment]
@Ivin-yang  How did you solved the authentication issue? I also have generated access token in /user/settings/applications. I don't know how to use this token.
