### ISSUE TITLE
/api/v1/ get 404

### ISSUE THREAD

**Issue by t-walker-wei** [gogs/docs-api#22]
Gogs Version: 0.11.86.0130
When I try to use rest api from gogs, I cannot use the api. the url : **http://{my gogs domain}/api/v1/**  got 404 error. Should I enable this feature in somewhere?

**Comment by t-walker-wei** [comment]
404 error cause by the wrong endpoint. Simple and stupid mistake.

**Comment by Taymindis** [comment]
Hi @t-walker-wei , I am also having the same issue. How should I fixed it

**Comment by t-walker-wei** [comment]
> Hi @t-walker-wei , I am also having the same issue. How should I fixed it

what api you have 404 error?

**Comment by Taymindis** [comment]
I setup gogs locally at Windows Server. When i try to access `http://localhost:3000/api/v1/` It got 404 not found
